CREATE TABLE city (
	city VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	city_lat VARCHAR NOT NULL,
	city_lng VARCHAR NOT NULL,
	city_population INTEGER NOT NULL,
	city_id INTEGER PRIMARY KEY
);

CREATE TABLE events (
	id SERIAL PRIMARY KEY,
	evt VARCHAR(255) NOT NULL,
	grp VARCHAR(255) NOT NULL,
	lnk VARCHAR(255) NOT NULL,
	attendees INTEGER NOT NULL,
	maploc VARCHAR(255) NOT NULL,
	city VARCHAR NOT NULL,
	subcity VARCHAR NOT NULL,
	state VARCHAR NOT NULL,
	street VARCHAR(255) NOT NULL,
	subcity_lat FLOAT,
	subcity_lng FLOAT,
	city_id INTEGER,
	FOREIGN KEY (city_id) REFERENCES city(city_id)
);

SELECT * FROM city;
SELECT * FROM events;
